Repository hjdivad/ember-m3, pull requests merged in 2020-08, with the labels that each got.

#822 Remove work around for Ember < 2.12 relying on `setOwner` enumerability
  addon/model.js
  addon/util.js
Labels: internal

#834 Avoid `checker.check` when project depends on ember-data
  index.js
Labels: bug

#837 Avoid checking project dependencies more than once per project
  index.js
Labels: enhancement

#840 Replace `new Object(null)` with `Object.create(null)`.
  addon/query-cache.js
  addon/services/store.js
  tests/unit/record-data-test.js
Labels: bug

#852 queryURL can resolve primitive values
  addon/query-cache.js
  tests/unit/query-cache-test.js
Labels: enhancement
