Repository hjdivad/ember-m3, pull requests merged in 2020-05, with the labels that each got.

#705 cleanup: BREAKING drop EmberData<3.16 support for 2.0
  README.md
  addon/-infra/features.js
  addon/-infra/packages.js
  addon/-infra/potential-features.js
  addon/-infra/potential-packages.js
  addon/record-data.js
  config/ember-try.js
  node-tests/unit/package-detection-test.js
  package.json
  src/debug-macros.js
  src/utils/project-package-helper.js
  yarn.lock
Labels: breaking

#719 updates readme with tests/dummy example and fix dummy
  README.md
  tests/dummy/app/routes/index.js
  tests/dummy/app/services/m3-schema.js
Labels: documentation

#732 queryURL learns to tolerate empty responses
  addon/query-cache.js
  tests/unit/query-cache-test.js
Labels: bug

#727 Assert against projection cycles
  addon/services/m3-schema-manager.js
  tests/unit/schema-manager-test.js
Labels: enhancement
