Repository hjdivad/ember-m3, pull requests merged in 2021-06, with the labels that each got.

#1121 Avoid invalid imports in production app tree
  index.js
Labels: bug

#1131 Ensure we do not add custom babel plugins multiple times
  index.js
Labels: bug

#1145 feat: make errors attribute configurable
  README.md
  addon/model.js
  addon/services/m3-schema-manager.js
  addon/services/m3-schema.js
  tests/unit/model/errors-attribute-test.js
  tests/unit/schema-manager-test.js
Labels: enhancement

#1168 Increase iterations in materialization perf test to decrease noise
  m3-perf-testing-app/app/routes/materializing.js
  m3-perf-testing-app/testem.js
  m3-perf-testing-app/tests/acceptance/materializing-test.js
Labels: internal

#1167 Allow custom ObjectProxy instances to be wrapped around an M3Model instance
  addon/resolve-attribute-util.js
  tests/unit/model/tracked-array-test.js
Labels: bug

#1157 Add CI workflow for running TracerBench
  .eslintrc.base.js
  .github/workflows/perf-check.yml
  scripts/create-comment.js
  scripts/post-comment.sh
Labels: internal

#1174 Make perfomance testing app more robust to slow tests
  m3-perf-testing-app/testem.js
  m3-perf-testing-app/tests/acceptance/materializing-test.js
Labels: internal
