Repository hjdivad/ember-m3, pull requests merged in 2021-03, with the labels that each got.

#1032 Adds support for native Proxy behind a canary feature flag
  .github/workflows/ci.yml
  addon/-infra/features.js
  addon/base-record-array.js
  addon/model.js
  index.js
  package.json
  src/debug-macros.js
  src/postpublish.js
  src/prepublish.js
  tests/index.html
  tests/test-helper.js
Labels: enhancement

#1022 only execute callback once per key for eachAttribute
  addon/record-data.js
  tests/unit/record-data-test.js
Labels: bug

#1041 Only execute callback once per key for eachAttribute (backport #1022)
  addon/record-data.js
  tests/unit/record-data-test.js
Labels: bug

#1047 Refactor warning capturing and testing.
  tests/helpers/warning-handler.js
  tests/test-helper.js
  tests/unit/model-test.js
Labels: internal
