Repository hjdivad/ember-m3, pull requests merged in 2021-08, with the labels that each got.

#1247 Don't trigger dot access deprecations when useNativeProperties hook isn't defined
  addon/services/m3-schema-manager.js
  tests/unit/model/native-access-test.js
Labels: bug

#1251 Cleanup the invalid errors test
  tests/unit/model-test.js
Labels: internal

#1242 Fix isDirty for inflight records and set _topModel to the proxy value
  addon/model.js
  addon/services/store.js
  tests/unit/model/saving-test.js
Labels: bug

#1249 Fix isSaving for embedded records when CUSTOM MODEL CLASS is on
  addon/model.js
  tests/unit/model/saving-test.js
Labels: bug

#1248 Add 'for' and 'since' to nativeProperties deprecation
  addon/model.js
Labels: bug

#1240 Fix for projected models resolving in projected arrays, when CUSTOM_MODEL_CLASS is on
  addon/utils/resolve.js
  tests/unit/model/projections/managed-arrays-test.js
Labels: bug

#1243 Fix isError and adapterError with CUSTOM_MODEL_CLASSES
  addon/model.js
  tests/unit/model/saving-test.js
Labels: bug

#1241 fix: skip this.errors.remove if useUnderlyingErrorsValue
  addon/model.js
  tests/unit/model/errors-attribute-test.js
Labels: bug

#1252 Add documentation for native property access
  DEPRECATIONS.md
  README.md
Labels: documentation

#1295 Fix isDeleted rollbackAttributes for Custom Model Class
  addon/record-data.js
  tests/unit/model/state-test.js
Labels: bug

#1296 Convert state tests to use native property access
  tests/helpers/prop-get.js
  tests/unit/model/state-test.js
Labels: internal

#1301 Sync projections and base model deleted state with CUSTOM_MODEL_CLASS
  addon/record-data.js
  tests/unit/projections/writing-test.js
Labels: bug, enhancement
